// ─────────────────────────────────────────────
// export.js — Texturas (ES) v1.0
// TEI XML, CSV, Markdown report generators + TEI import
// Reads: EMOTIONS, T from config.js
// Exports: genTEI, genCorpusTEI, genCSV, genReport, parseTEIImport, esc, csvQ, dlFile
// ─────────────────────────────────────────────

// ── Helpers ──
function esc(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function csvQ(v) {
  var s = String(v != null ? v : "");
  if (s.indexOf(",") >= 0 || s.indexOf('"') >= 0 || s.indexOf("\n") >= 0) {
    return '"' + s.replace(/"/g, '""') + '"';
  }
  return s;
}

function dlFile(content, filename, mime) {
  var blob = new Blob([content], { type: mime || "text/plain;charset=utf-8" });
  var url = URL.createObjectURL(blob);
  var a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ── TEI XML (single document, inline annotation) ──
function genTEI(docLabel, result) {
  var enriched = result.enriched;
  var lines = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<TEI xmlns="http://www.tei-c.org/ns/1.0">');
  lines.push('<teiHeader>');
  lines.push('  <fileDesc>');
  lines.push('    <titleStmt><title>' + esc(docLabel) + '</title></titleStmt>');
  lines.push('    <publicationStmt><p>Generated by Texturas v1.0</p></publicationStmt>');
  lines.push('    <sourceDesc><p>Texturas multi-layered textual analysis (Spanish)</p></sourceDesc>');
  lines.push('  </fileDesc>');
  lines.push('  <profileDesc>');
  lines.push('    <langUsage><language ident="es">Spanish</language></langUsage>');
  lines.push('  </profileDesc>');
  lines.push('</teiHeader>');
  lines.push('<text xml:lang="es">');
  lines.push('<body>');

  // Inline annotation: each word wrapped in <w> with feature structures
  var weaveEnriched = result.weaveEnriched || [enriched];
  for (var pi = 0; pi < weaveEnriched.length; pi++) {
    var para = weaveEnriched[pi];
    lines.push('<p>');
    for (var ti = 0; ti < para.length; ti++) {
      var tok = para[ti];
      if (tok.type === "s" || (tok.stop && tok.surface && tok.surface.trim() === "")) {
        lines.push(' ');
        continue;
      }
      if (tok.type === "x" || tok.stop) {
        lines.push(esc(tok.surface));
        continue;
      }
      // Content word with annotations
      var attrs = ' lemma="' + esc(tok.lemma) + '" pos="' + esc(tok.pos) + '"';
      lines.push('<w' + attrs + '>');
      lines.push('  <fs>');
      lines.push('    <f name="freq"><numeric value="' + (tok.freq || 0) + '"/></f>');
      lines.push('    <f name="rel"><numeric value="' + (tok.rel || 0).toFixed(4) + '"/></f>');
      if (tok.polarity !== null && tok.polarity !== undefined) {
        lines.push('    <f name="polarity"><numeric value="' + tok.polarity.toFixed(4) + '"/></f>');
      }
      if (tok.arousal !== null && tok.arousal !== undefined) {
        lines.push('    <f name="arousal"><numeric value="' + tok.arousal.toFixed(4) + '"/></f>');
      }
      if (tok.comm >= 0) {
        lines.push('    <f name="community"><numeric value="' + tok.comm + '"/></f>');
      }
      if (tok.emolex) {
        var emos = [];
        for (var ei = 0; ei < EMOTIONS.length; ei++) {
          if (tok.emolex[EMOTIONS[ei]]) emos.push(EMOTIONS[ei]);
        }
        if (emos.length > 0) {
          lines.push('    <f name="emotions"><string>' + esc(emos.join(",")) + '</string></f>');
        }
      }
      lines.push('  </fs>');
      lines.push('  ' + esc(tok.surface));
      lines.push('</w>');
    }
    lines.push('</p>');
  }

  lines.push('</body>');
  lines.push('</text>');
  lines.push('</TEI>');
  return lines.join("\n");
}

// ── TEI Corpus (multiple documents) ──
function genCorpusTEI(docs, results) {
  var lines = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<teiCorpus xmlns="http://www.tei-c.org/ns/1.0">');
  lines.push('<teiHeader>');
  lines.push('  <fileDesc>');
  lines.push('    <titleStmt><title>Texturas Corpus</title></titleStmt>');
  lines.push('    <publicationStmt><p>Generated by Texturas v1.0</p></publicationStmt>');
  lines.push('    <sourceDesc><p>Multi-document analysis (Spanish)</p></sourceDesc>');
  lines.push('  </fileDesc>');
  lines.push('  <profileDesc>');
  lines.push('    <langUsage><language ident="es">Spanish</language></langUsage>');
  lines.push('  </profileDesc>');
  lines.push('</teiHeader>');
  for (var i = 0; i < docs.length; i++) {
    var d = docs[i];
    if (results[d.id]) {
      lines.push(genTEI(d.label, results[d.id]));
    }
  }
  lines.push('</teiCorpus>');
  return lines.join("\n");
}

// ── CSV Export ──
function genCSV(docLabel, result) {
  var enriched = result.enriched;
  var header = ["surface", "lemma", "pos", "stop", "freq", "rel", "polarity", "arousal", "community"];
  for (var ei = 0; ei < EMOTIONS.length; ei++) {
    header.push("emo_" + EMOTIONS[ei]);
  }
  var rows = [header.map(csvQ).join(",")];

  for (var i = 0; i < enriched.length; i++) {
    var tok = enriched[i];
    var row = [
      csvQ(tok.surface), csvQ(tok.lemma), csvQ(tok.pos), csvQ(tok.stop ? 1 : 0),
      csvQ(tok.freq || 0), csvQ((tok.rel || 0).toFixed(4)),
      csvQ(tok.polarity !== null ? tok.polarity.toFixed(4) : ""),
      csvQ(tok.arousal !== null ? tok.arousal.toFixed(4) : ""),
      csvQ(tok.comm >= 0 ? tok.comm : "")
    ];
    for (var ei2 = 0; ei2 < EMOTIONS.length; ei2++) {
      row.push(csvQ(tok.emolex && tok.emolex[EMOTIONS[ei2]] ? 1 : 0));
    }
    rows.push(row.join(","));
  }
  return rows.join("\n");
}

// ── Markdown Report ──
function genReport(docLabel, result) {
  var lines = [];
  lines.push("# Texturas — Informe de An\u00E1lisis");
  lines.push("");
  lines.push("**Documento:** " + docLabel);
  lines.push("**Tokens totales:** " + (result.tw || 0).toLocaleString());
  lines.push("**Palabras de contenido:** " + (result.filtLem ? result.filtLem.length : 0).toLocaleString());
  lines.push("**Top N:** " + (result.topWords ? result.topWords.length : 0));
  lines.push("");

  // Top words
  lines.push("## Palabras m\u00E1s frecuentes");
  lines.push("");
  if (result.topWords) {
    for (var i = 0; i < Math.min(result.topWords.length, 25); i++) {
      var w = result.topWords[i];
      var rel = result.relevanceMap ? (result.relevanceMap[w[0]] || 0).toFixed(1) : "—";
      lines.push((i + 1) + ". **" + w[0] + "** — frec: " + w[1] + ", relev: " + rel);
    }
  }
  lines.push("");

  // Communities
  if (result.commMap) {
    lines.push("## Comunidades (Louvain)");
    lines.push("");
    var comms = {};
    var k;
    for (k in result.commMap) {
      if (result.commMap.hasOwnProperty(k)) {
        var c = result.commMap[k];
        if (!comms[c]) comms[c] = [];
        comms[c].push(k);
      }
    }
    var commIds = Object.keys(comms).sort(function(a, b) { return +a - +b; });
    for (var ci = 0; ci < commIds.length; ci++) {
      var members = comms[commIds[ci]];
      lines.push("- **Comunidad " + commIds[ci] + "** (" + members.length + "): " + members.slice(0, 15).join(", ") + (members.length > 15 ? "..." : ""));
    }
    lines.push("");
  }

  // Bigrams
  if (result.ng2 && result.ng2.length > 0) {
    lines.push("## Bigramas principales");
    lines.push("");
    for (var bi = 0; bi < Math.min(result.ng2.length, 15); bi++) {
      lines.push("- " + result.ng2[bi][0] + " (" + result.ng2[bi][1] + ")");
    }
    lines.push("");
  }

  // Trigrams
  if (result.ng3 && result.ng3.length > 0) {
    lines.push("## Trigramas principales");
    lines.push("");
    for (var tri = 0; tri < Math.min(result.ng3.length, 10); tri++) {
      lines.push("- " + result.ng3[tri][0] + " (" + result.ng3[tri][1] + ")");
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generado por Texturas v1.0*");
  return lines.join("\n");
}

// ── TEI Import Parser ──
function parseTEIImport(xmlString) {
  var parser = new DOMParser();
  var doc = parser.parseFromString(xmlString, "application/xml");

  // Check for parse errors
  var err = doc.querySelector("parsererror");
  if (err) return { error: "Error al parsear XML: " + err.textContent.slice(0, 100) };

  // Handle corpus or single TEI
  var teiElements = doc.querySelectorAll("TEI");
  if (!teiElements.length) return { error: "No se encontraron elementos TEI." };

  var results = [];
  for (var ti = 0; ti < teiElements.length; ti++) {
    var tei = teiElements[ti];
    var titleEl = tei.querySelector("titleStmt title");
    var label = titleEl ? titleEl.textContent : "Documento " + (ti + 1);

    // Extract text from <p> elements, reconstructing from <w> tags
    var paragraphs = tei.querySelectorAll("body p");
    var textParts = [];
    for (var pi = 0; pi < paragraphs.length; pi++) {
      var pText = "";
      var nodes = paragraphs[pi].childNodes;
      for (var ni = 0; ni < nodes.length; ni++) {
        var node = nodes[ni];
        if (node.nodeType === 3) {
          // Text node
          pText += node.textContent;
        } else if (node.nodeName === "w") {
          // Word element — extract surface text (last text child)
          var wText = "";
          var wChildren = node.childNodes;
          for (var wi = wChildren.length - 1; wi >= 0; wi--) {
            if (wChildren[wi].nodeType === 3 && wChildren[wi].textContent.trim()) {
              wText = wChildren[wi].textContent.trim();
              break;
            }
          }
          pText += wText;
        }
      }
      textParts.push(pText.trim());
    }

    results.push({
      label: label,
      text: textParts.join("\n\n")
    });
  }

  return { docs: results };
}
